export const STORAGE_KEYS = {
  auth: '@heyattrangi/auth',
  profile: '@heyattrangi/profile',
  mood: '@heyattrangi/mood',
  therapists: '@heyattrangi/therapists',
  booking: '@heyattrangi/booking',
  sessions: '@heyattrangi/sessions',
  payments: '@heyattrangi/payments',
  billing: '@heyattrangi/billing',
  chat: '@heyattrangi/chat',
  notifications: '@heyattrangi/notifications',
  onboarding: '@heyattrangi/onboarding',
  recentTherapistSearches: '@heyattrangi/recent-therapist-searches',
  authToken: '@heyattrangi/auth-token',
  journal: '@heyattrangi/journal',
  wellness: '@heyattrangi/wellness',
  preferences: '@heyattrangi/preferences',
  offlineQueue: '@heyattrangi/offline-queue',
  appConfig: '@heyattrangi/app-config',
  search: '@heyattrangi/search',
  personalization: '@heyattrangi/personalization',
  engagement: '@heyattrangi/engagement',
  institution: '@heyattrangi/institution',
  permissions: '@heyattrangi/permissions',
  devTools: '@heyattrangi/dev-tools',
} as const;
