import { LinkingOptions } from '@react-navigation/native';
import * as Linking from 'expo-linking';
import { env } from '../config/env';
import { RootStackParamList } from './types';

const prefix = Linking.createURL('/');

/**
 * Deep-link map for heyattrangi:// and https://heyattrangi.app
 * Nested under Auth / Onboarding / MainApp gates.
 */
export const linking: LinkingOptions<RootStackParamList> = {
  prefixes: [prefix, ...env.DEEP_LINK_PREFIXES],
  config: {
    screens: {
      Auth: {
        screens: {
          Welcome: 'welcome',
          SignIn: 'sign-in',
          SignUpBasic: 'sign-up',
          ForgotPassword: 'forgot-password',
        },
      },
      Onboarding: {
        screens: {
          PersonalWelcome: 'onboarding',
        },
      },
      MainApp: {
        screens: {
          MainTabs: {
            screens: {
              HomeTab: 'home',
              ChatTab: 'companion',
              MoodTab: 'mood',
              TherapistsTab: 'therapists',
              ProfileTab: 'profile',
              InstitutionTab: 'campus',
            },
          },
          TherapistProfile: 'therapist/:therapistId',
          Sessions: 'sessions',
          WaitingRoom: 'session/:sessionId/waiting',
          SessionPermissions: 'session/:sessionId/permissions',
          CameraPreview: 'session/:sessionId/preview',
          VideoSession: 'session/:sessionId/live',
          SessionComplete: 'session/:sessionId/complete',
          SessionFeedback: 'session/:sessionId/feedback',
          BookingConfirmation: 'booking/confirmed',
          JournalHome: 'journal',
          JournalEntry: 'journal/entry/:entryId?',
          WellnessHub: 'wellness',
          WellnessJourney: 'wellness/journey',
          HabitTracking: 'habits',
          PersonalInsights: 'insights',
          RecommendationFeed: 'recommendations',
          DashboardCustomize: 'dashboard/customize',
          ProgressDashboard: 'progress',
          BadgeCollection: 'badges',
          WeeklyChallenges: 'challenges',
          MonthlyGoals: 'goals/monthly',
          EngagementRewards: 'rewards',
          MilestoneTimeline: 'milestones',
          InstitutionDashboard: 'institution',
          InstitutionProfile: 'institution/profile',
          CampusPrograms: 'institution/programs',
          InstitutionAnnouncements: 'institution/announcements',
          CampusResources: 'institution/resources',
          InstitutionNotifications: 'institution/notifications',
          RoleSwitcher: 'role',
          StudentWellnessDashboard: 'institution/student',
          WellnessReportsHub: 'reports',
          WellnessReportsDashboard: 'reports/dashboard',
          ReportDetail: 'reports/:kind',
          ReportExportData: 'reports/export',
          InstitutionReports: 'reports/institution',
          ParentReports: 'reports/parent',
          TrustedCircle: 'family',
          InviteContact: 'family/invite',
          RelationshipManagement: 'family/member/:memberId',
          CirclePermissions: 'family/permissions',
          EmergencySharing: 'family/emergency-sharing',
          WellnessSharing: 'family/wellness-sharing',
          GuardianView: 'family/guardian',
          CaregiverDashboard: 'family/caregiver',
          TrustedContacts: 'family/trusted',
          EmergencyContacts: 'family/emergency',
          CommunityHome: 'community',
          CommunityDetail: 'community/:communityId',
          CommunityGroups: 'community/groups',
          CommunityEvents: 'community/events',
          PeerDiscussions: 'community/discussions',
          AnonymousMode: 'community/anonymous',
          ModerationQueue: 'community/moderation',
          ContentReport: 'community/report',
          GroupWellness: 'community/group-wellness',
          SavedPosts: 'community/saved',
          TherapistDashboard: 'portal',
          TherapistSchedule: 'portal/schedule',
          TherapistAppointments: 'portal/appointments',
          TherapistAvailability: 'portal/availability',
          TherapistClientList: 'portal/clients',
          SessionNotesPlaceholder: 'portal/notes/:appointmentId',
          SessionAiSummaryPlaceholder: 'portal/ai-summary/:appointmentId',
          PortalReports: 'portal/reports',
          AdminDashboard: 'portal/admin',
          InstitutionAnalytics: 'portal/analytics',
          DevToolsMenu: 'devtools',
          ComponentGallery: 'devtools/gallery',
          ComponentShowcase: 'devtools/showcase',
          ThemePlayground: 'devtools/theme',
          TypographyPreview: 'devtools/typography',
          ColorPalettePreview: 'devtools/colors',
          AnimationPreview: 'devtools/animation',
          EmptyStateGallery: 'devtools/empty',
          LoadingGallery: 'devtools/loading',
          DialogGallery: 'devtools/dialogs',
          FeatureToggle: 'devtools/flags',
          MockApiSwitch: 'devtools/mock-api',
          EnvironmentSwitch: 'devtools/env',
          DebugScreen: 'devtools/debug',
          PerformanceMonitor: 'devtools/performance',
          NetworkInspector: 'devtools/network',
          UiStatesDemo: 'devtools/ui-states',
          ConversationHistory: 'companion/history',
          ConversationSearch: 'companion/search',
          ConversationExport: 'companion/export/:conversationId',
          AiMemoryViewer: 'companion/memory',
          AiTimeline: 'companion/timeline',
          ConversationTemplates: 'companion/templates',
          VoiceConversation: 'companion/voice',
          AiCompanionSettings: 'companion/settings',
          MoodHistory: 'mood/history',
          MoodAnalytics: 'mood/analytics',
          Settings: 'settings',
          AppSearch: 'search',
          SearchHistory: 'search/history',
          HelpCenter: 'help',
          HelpArticle: 'help/:slug',
          Notifications: 'notifications/preferences',
          NotificationCenter: 'notifications',
          ActivityTimeline: 'activity',
          AccountManagement: 'account',
          BillingInvoices: 'billing',
          Subscription: 'subscription',
          SubscriptionComparison: 'subscription/compare',
          BillingHistory: 'billing/history',
          Wallet: 'wallet',
          Refunds: 'refunds',
          CareCredits: 'credits',
        },
      },
    },
  },
};
